server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: transaction-service
          uri: http://transaction-service:8082
          predicates:
            - Path=/transaction/**
          filters:
            - StripPrefix=1

        - id: atm-service
          uri: http://atm-service:8083
          predicates:
            - Path=/atm/**
          filters:
            - StripPrefix=1
